### PR TITLE
GraphQL 4 Compatability

### PR DESCRIPTION
**Pull request by unclecheese**

### CODE REVIEW

**Comment by emteknetnz** [comment]
Should this PR also update composer.json so that requires graphql:^5, or at least dev-master?  

Things won't go to well if this gets included on a project that uses graphql 4

**Comment by unclecheese** [comment]
The idea is that it can work with both, which is why we have the `classexists` guards.

(all the core modules will work with both)

**Comment by emteknetnz** [comment]
Sorry I don't follow

image

So if I have GraphQL 4 installed, because of the removed code, the `Manager.frameworktest` is no longer going to be configured properly?

**Comment by unclecheese** [comment]
Gah, sorry. Had some changes that I thought I pushed up but got rejected. Have another look and it will make more sense now. :)

**Comment by emteknetnz** [comment]
Seems legit

You'll probably want to tag this 0.2.0 so that it can be used in [.travis files ](https://github.com/silverstripe/silverstripe-asset-admin/blob/1/.travis.yml#L60)

**Pull request merged**
